[project]
name = "pawbit"
description = ""
authors = []
telemetry = true
cache_dir = "./.cache"

[contracts.sip-010-trait]
path = "contracts/traits/sip-010-trait.clar"
epoch = "latest"

[contracts.pawbit]
path = "contracts/pawbit.clar"
depends_on = ["sip-010-trait"]
epoch = "latest"
[repl.analysis]
passes = ["check_checker"]
check_checker = { trusted_sender = false, trusted_caller = false, callee_filter = false }

# Check-checker settings:
# trusted_sender: if true, inputs are trusted after tx_sender has been checked.
# trusted_caller: if true, inputs are trusted after contract-caller has been checked.
# callee_filter: if true, untrusted data may be passed into a private function without a
# warning, if it gets checked inside. This check will also propagate up to the
# caller.
# More informations: https://www.hiro.so/blog/new-safety-checks-in-clarinet
